# -*- coding: utf-8 -*-
"""07-01-2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SkWS0i16Uw-sYldPssvz1-AFEk3iYTOa
"""

list=['apple','banana','cherries']
print(list)

"""# New Section"""

from typing import Concatenate
List1=['apple','banana','cherries']
List2=[1,2,3,4]
sum=List1+List2
print(sum)

List1=['apple','banana','cherries']
List1[1:2]

my_int = 45
print("Original integer=", my_int)

my_list= [1, 'hello', 3.14, True]
print("Original list=", my_list)
my_list.append('world')
print("list after appending 'world'=", my_list)
my_list.remove(3.14)
print("list after removing 3.14=", my_list)

my_tuple = (1, 'hello', 3.14, True)
print("Original tuple=", my_tuple)
print("First element:", my_tuple[0])
print("last element:", my_tuple[-1])

i=1
while i <= 5:
  print(i)
  i += 1

for i in range(1,6):
  print(i)

from pathlib import PureWindowsPath
number= int(input("enter a number: "))
if number>0:
  print("number is positive")
elif number<0:
    print("number is negative")
else:
      print("number is zero")

def greet(name):
  "this function takes a name as a argument and prints a greeting"
  print(f"Hello from function, {name}!")
greet("keerthi")

def greet(name):
  print(f"Hello from function, {name}!")
  print(dir(str))

a='Hello World!'
b=a.lower()
print(b)

a='hello world!'
b=a.title()
print(b)

a='hello world!'
b=a.replace('hello','hi')
print(b)

a='123kfkkf'
b= a.isdigit()
print(b)

a=range(10)
print(a)

a=range(10)
b=list(a)
print(b)

#start, stop then steps
my_list=list(range(1,10,2))
print(my_list)

def add_numbers(a,b):
  return a+b
result=add_numbers(5,3)
print(result)

#function with default
def greet(name, greeting="Hello"):
  print(f"{greeting}, {name}!")

#function with *args
def calculate_sum(*args):
  total=sum(args)
  return total
print("sum of 1,2,3:", calculate_sum(1,2,3))
print("sum of 1,2,3,4:", calculate_sum(1,2,3,4))

correct_username='admin'
correct_password='password123'
while True:
  username=input("enter username: ")
  password=input("enter password: ")
  if username==correct_username and password==correct_password:
    print("login successful")
    break
  else:
    print("invalid username or password")

a='Hello World!'
b=a.capitalize()
print(b)

a=range(1,10)
b=tuple(a)
print(b)

my_list = [0, 1, 2, 3, 4, 5]
print(my_list[1:4])

def add_numbers(a,b):
  return a*b
result=add_numbers(5,3)
print(result)