# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SkWS0i16Uw-sYldPssvz1-AFEk3iYTOa
"""

list=['apple','banana','cherries']
print(list)

"""# New Section"""

from typing import Concatenate
List1=['apple','banana','cherries']
List2=[1,2,3,4]
sum=List1+List2
print(sum)

List1=['apple','banana','cherries']
List1[1:2]

my_int = 45
print("Original integer=", my_int)

my_list= [1, 'hello', 3.14, True]
print("Original list=", my_list)
my_list.append('world')
print("list after appending 'world'=", my_list)
my_list.remove(3.14)
print("list after removing 3.14=", my_list)

my_tuple = (1, 'hello', 3.14, True)
print("Original tuple=", my_tuple)
print("First element:", my_tuple[0])
print("last element:", my_tuple[-1])

i=1
while i <= 5:
  print(i)
  i += 1

for i in range(1,6):
  print(i)

from pathlib import PureWindowsPath
number= int(input("enter a number: "))
if number>0:
  print("number is positive")
elif number<0:
    print("number is negative")
else:
      print("number is zero")

def greet(name):
  "this function takes a name as a argument and prints a greeting"
  print(f"Hello from function, {name}!")
greet("keerthi")

